### PR TITLE
Add gracc-reprocess tool

### PR DESCRIPTION
**Pull request by retzkek**
`gracc-reprocess` reads `RawXML` records from Elasticsearch and sends them to a GRACC collector.

### CODE REVIEW

**Comment by retzkek** [comment]
Note that this doesn't have the option to *delete* records, since I don't think we'd ever want to do that without first verifying records were reprocessed correctly. Deleting records can be as simple as 
```
curl -XPOST "http://localhost:9200/gracc.osg.raw3-2017.06/_delete_by_query?pretty" -d'
{
  "query":{
    "query_string":{
      "query":"NOT _exists_:EndTime"
    }
  }
}'
```

(of course first do a `_search` with that query or look at it in Kibana and make sure its right)

**Comment by bbockelm** [comment]
What's the over/under on doing this versus reprocessing based on backups?

**Comment by retzkek** [comment]
With backups you'll have to read every record and either reprocess them all or filter them manually. I don't think we really want to reprocess *every* record... This way we have a handy-dandy search engine to find only the affected records

**Comment by bbockelm** [comment]
I figured there was something along those lines... can you file a JIRA ticket to have Marian update the operational docs suggesting when one should use this tool versus the backup-centric tools?

(Also, it seems that the README is excellent - I wonder if we could automatically embed this into the github-pages docs?)

**Pull request merged**
