### PR TITLE
Initial commit of Terraform config for OpenSearch

### PR DESCRIPTION
**Pull request by jthiltges**

### CODE REVIEW

**Comment by djw8605** [comment]
Need to include the resources directory with the index templates.

**Comment by jthiltges** [comment]
Oops, thanks. Added.

**Review by djw8605 — APPROVED** [review]
LGTM.  Though, I wonder if we could leave everything in the main in there, and do some json replacement.  IE, have a json config file that is distributed out of band with passwords in it?

**Comment by jthiltges** [comment]
At the moment, the users are being added by [internal_users.yml](https://github.com/opensciencegrid/tiger-osg-config/blob/master/manifests/tiger/gracc-dev/opensearch-cluster/test1-securityconfig.yaml#L33).

I think when the operator updates the security config, it re-runs `securityadmin`, which [wipes out](https://opensearch.org/docs/latest/security/configuration/security-admin#a-word-of-caution) any users created via REST.

**Comment by djw8605** [comment]
Good point.  Is there docs on how to create those password hashes?

**Comment by jthiltges** [comment]
> Good point. Is there docs on how to create those password hashes?

Indirectly. The [config](https://github.com/opensciencegrid/tiger-osg-config/blob/master/manifests/tiger/gracc-dev/opensearch-cluster/test1-securityconfig.yaml#L37) includes a link to the [docs](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#custom-admin-user), which has a bcrypt python snippet.

**Pull request merged**
